name: 'ROS 2 Clang tidy'
author: 'Guillem Torrente (tmguillem)'
description: 'Github Action that builds a ROS 2 package and executes Clang tidy in it'
branding:
  icon: 'activity'  
  color: 'black'

runs:
  using: 'docker'
  image: 'Dockerfile'